package info.esblurock.reaction.parse.objects.two;

public class ObjectAndPredicateParseObject extends TwoParameterParseObject {

	public ObjectAndPredicateParseObject() {
		super("object","predicate");
	}
	/**
	 * A description of the filter generated by this class.
	 */
	public String toString() {
		return "object=input1 and predicate=input2";
	}

}
