package info.esblurock.reaction.parse.objects.two;

import java.util.StringTokenizer;

import com.google.appengine.api.datastore.Query.CompositeFilterOperator;
import com.google.appengine.api.datastore.Query.Filter;
import com.google.appengine.api.datastore.Query.FilterOperator;
import com.google.appengine.api.datastore.Query.FilterPredicate;

import info.esblurock.reaction.parse.objects.ParseObject;

public class TwoParameterParseObject extends ParseObject {
	protected String param1;
	protected String param2;
	public TwoParameterParseObject(String param1, String param2) {
		this.param1 = param1;
		this.param2 = param2;
	}
	/** return the Filter to be used in the query
	 * 
	 * @param input The input parameter to be used in the Filter.
	 * @return The filter
	 */
	public Filter getFilter(String input) {
		StringTokenizer tok = new StringTokenizer(" ");
		String input1 = tok.nextToken();
		String input2 = tok.nextToken();
		Filter subjectfilter1 =
				  new FilterPredicate(param1,FilterOperator.EQUAL,input1);
		Filter subjectfilter2 =
				  new FilterPredicate(param2,FilterOperator.EQUAL,input2);
		Filter filter = CompositeFilterOperator.and(subjectfilter1,subjectfilter2);
		return filter;
	}
	/**
	 * A description of the filter generated by this class.
	 */
	public String toString() {
		return "Two parameters to match: " + param1 + ", " + param2;
	}

}
