#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:./war/WEB-INF/lib/gwt-dev.jar:/opt/Google/gwt-2.7.0/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src info.esblurock.reaction.client.ui.resource.TopPageConstants  ;

